package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.04 05:11:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyllytTest {



  // Generated by ComTest BEGIN
  /** 
   * testEquals60 
   * @throws TietoException when error
   */
  @Test
  public void testEquals60() throws TietoException {    // Hyllyt: 60
    Hyllyt tama = new Hyllyt(); 
    Hyllyt toinen = new Hyllyt(); 
    tama.lisaa(new Hylly("1|1|JAG|2")); toinen.lisaa(new Hylly("1|1|JAG|2")); 
    assertEquals("From: Hyllyt line: 65", true, tama.equals(toinen)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna87 
   * @throws TietoException when error
   */
  @Test
  public void testTallenna87() throws TietoException {    // Hyllyt: 87
    Hyllyt uusi = new Hyllyt(); 
    Hyllyt toka = new Hyllyt(); 
    uusi.lueTiedostosta("testFiles/testHyllyt.dat"); 
    uusi.tallenna("testFiles/testHyllytUlos.dat"); 
    toka.lueTiedostosta("testFiles/testHyllytUlos.dat"); 
    assertEquals("From: Hyllyt line: 94", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/testHyllytEri.dat"); 
    System.out.println(uusi.equals(toka)); 
    assertEquals("From: Hyllyt line: 97", false, uusi.equals(toka)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta118 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostosta118() throws TietoException {    // Hyllyt: 118
    Hyllyt uusi = new Hyllyt(); 
    Hyllyt toka = new Hyllyt(); 
    uusi.lueTiedostosta("testFiles/testHyllyt.dat"); 
    toka.lueTiedostosta("testFiles/testHyllyt.dat"); 
    assertEquals("From: Hyllyt line: 124", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/testHyllytEri.dat"); 
    assertEquals("From: Hyllyt line: 126", false, uusi.equals(toka)); 
    assertEquals("From: Hyllyt line: 127", 4, uusi.getLkm()); 
    assertEquals("From: Hyllyt line: 128", "1|1|JAG|2", uusi.anna(0).toString()); 
  } // Generated by ComTest END
}