package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.06 11:56:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyllytTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa29() throws TietoException {    // Hyllyt: 29
    Hyllyt hyllyt = new Hyllyt(); 
    Hylly h1 = new Hylly(), h2 = new Hylly(), h3 = new Hylly(); 
    hyllyt.lisaa(h1); hyllyt.lisaa(h2); hyllyt.lisaa(h3); 
    assertEquals("From: Hyllyt line: 34", 3, hyllyt.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTyhjenna53 
   * @throws TietoException when error
   */
  @Test
  public void testTyhjenna53() throws TietoException {    // Hyllyt: 53
    Hyllyt hyl = new Hyllyt(); 
    hyl.lisaa(new Hylly()); 
    hyl.lisaa(new Hylly()); 
    hyl.lisaa(new Hylly()); 
    assertEquals("From: Hyllyt line: 59", 3, hyl.getLkm()); 
    hyl.tyhjenna(); 
    assertEquals("From: Hyllyt line: 61", 0, hyl.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa75 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa75() throws TietoException {    // Hyllyt: 75
    Hyllyt hyl = new Hyllyt(); 
    hyl.lisaa("1|2|GWB|0"); hyl.lisaa("2|1|ABC|0"); 
    assertEquals("From: Hyllyt line: 79", 2, hyl.getLkm()); 
    assertEquals("From: Hyllyt line: 80", "1|2|GWB|0", hyl.anna(0).toString()); 
    assertEquals("From: Hyllyt line: 81", "2|1|ABC|0", hyl.haeId(2).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEquals102 
   * @throws TietoException when error
   */
  @Test
  public void testEquals102() throws TietoException {    // Hyllyt: 102
    Hyllyt tama = new Hyllyt(); 
    Hyllyt toinen = new Hyllyt(); 
    tama.lisaa(new Hylly("1|1|JAG|2")); toinen.lisaa(new Hylly("1|1|JAG|2")); 
    assertEquals("From: Hyllyt line: 107", true, tama.equals(toinen)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna126 
   * @throws TietoException when error
   */
  @Test
  public void testTallenna126() throws TietoException {    // Hyllyt: 126
    Hyllyt uusi = new Hyllyt(); 
    Hyllyt toka = new Hyllyt(); 
    uusi.lueTiedostosta("testFiles/hyllyt.dat"); 
    uusi.tallenna("testFiles/hyllytUlos.dat"); 
    toka.lueTiedostosta("testFiles/hyllytUlos.dat"); 
    assertEquals("From: Hyllyt line: 133", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/hyllytEri.dat"); 
    assertEquals("From: Hyllyt line: 135", false, uusi.equals(toka)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta166 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostosta166() throws TietoException {    // Hyllyt: 166
    Hyllyt uusi = new Hyllyt(); 
    Hyllyt toka = new Hyllyt(); 
    uusi.lueTiedostosta("testFiles/hyllyt.dat"); 
    toka.lueTiedostosta("testFiles/hyllyt.dat"); 
    assertEquals("From: Hyllyt line: 172", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/hyllytEri.dat"); 
    assertEquals("From: Hyllyt line: 174", false, uusi.equals(toka)); 
  } // Generated by ComTest END
}