package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.26 17:19:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyllyTest {



  // Generated by ComTest BEGIN
  /** testLisaa46 */
  @Test
  public void testLisaa46() {    // Hylly: 46
    Hylly uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 48", 0, uusi.getMaara()); 
    uusi.lisaa(); 
    assertEquals("From: Hylly line: 50", 1, uusi.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVahenna62 */
  @Test
  public void testVahenna62() {    // Hylly: 62
    Hylly uusi = new Hylly(1, 2, "JAG", 3); 
    assertEquals("From: Hylly line: 64", 3, uusi.getMaara()); 
    uusi.vahenna(); 
    assertEquals("From: Hylly line: 66", 2, uusi.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString107 */
  @Test
  public void testToString107() {    // Hylly: 107
    Hylly uusi = new Hylly(); 
    assertEquals("From: Hylly line: 109", "0|0||0", uusi.toString()); 
    uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 111", "1|2|JAG|0", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTiedot124 */
  @Test
  public void testGetTiedot124() {    // Hylly: 124
    Hylly uusi = new Hylly(); 
    assertEquals("From: Hylly line: 126", "|0", uusi.getTiedot()); 
    uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 128", "JAG|0", uusi.getTiedot()); 
  } // Generated by ComTest END
}