package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.22 20:20:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyllytTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa29() throws TietoException {    // Hyllyt: 29
    Hyllyt hyllyt = new Hyllyt(); 
    Hylly h1 = new Hylly(), h2 = new Hylly(), h3 = new Hylly(); 
    hyllyt.lisaa(h1); hyllyt.lisaa(h2); hyllyt.lisaa(h3); 
    assertEquals("From: Hyllyt line: 34", 3, hyllyt.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaaTaiMuuta57 
   * @throws TietoException when error
   */
  @Test
  public void testLisaaTaiMuuta57() throws TietoException {    // Hyllyt: 57
    Hyllyt hyllyt = new Hyllyt(); 
    Hylly uusi = new Hylly(1, 4, "UUU", 0); 
    hyllyt.lueTiedostosta("testFiles/hyllyt.dat"); 
    Hylly viite = hyllyt.lisaaTaiMuuta(uusi); 
    assertEquals("From: Hyllyt line: 63", "1|4|UUU|0", viite.toString()); 
    assertEquals("From: Hyllyt line: 64", true, hyllyt.haeId(1).equals(uusi)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTyhjenna82 
   * @throws TietoException when error
   */
  @Test
  public void testTyhjenna82() throws TietoException {    // Hyllyt: 82
    Hyllyt hyl = new Hyllyt(); 
    hyl.lisaa(new Hylly()); 
    hyl.lisaa(new Hylly()); 
    hyl.lisaa(new Hylly()); 
    assertEquals("From: Hyllyt line: 88", 3, hyl.getLkm()); 
    hyl.tyhjenna(); 
    assertEquals("From: Hyllyt line: 90", 0, hyl.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa104 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa104() throws TietoException {    // Hyllyt: 104
    Hyllyt hyl = new Hyllyt(); 
    hyl.lisaa("1|2|GWB|0"); hyl.lisaa("2|1|ABC|0"); 
    assertEquals("From: Hyllyt line: 108", 2, hyl.getLkm()); 
    assertEquals("From: Hyllyt line: 109", "1|2|GWB|0", hyl.anna(0).toString()); 
    assertEquals("From: Hyllyt line: 110", "2|1|ABC|0", hyl.haeId(2).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEquals131 
   * @throws TietoException when error
   */
  @Test
  public void testEquals131() throws TietoException {    // Hyllyt: 131
    Hyllyt tama = new Hyllyt(); 
    Hyllyt toinen = new Hyllyt(); 
    tama.lisaa(new Hylly("1|1|JAG|2")); toinen.lisaa(new Hylly("1|1|JAG|2")); 
    assertEquals("From: Hyllyt line: 136", true, tama.equals(toinen)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna155 
   * @throws TietoException when error
   */
  @Test
  public void testTallenna155() throws TietoException {    // Hyllyt: 155
    Hyllyt uusi = new Hyllyt(); 
    Hyllyt toka = new Hyllyt(); 
    uusi.lueTiedostosta("testFiles/hyllyt.dat"); 
    uusi.tallenna("testFiles/hyllytUlos.dat"); 
    toka.lueTiedostosta("testFiles/hyllytUlos.dat"); 
    assertEquals("From: Hyllyt line: 162", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/hyllytEri.dat"); 
    assertEquals("From: Hyllyt line: 164", false, uusi.equals(toka)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta195 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostosta195() throws TietoException {    // Hyllyt: 195
    Hyllyt uusi = new Hyllyt(); 
    Hyllyt toka = new Hyllyt(); 
    uusi.lueTiedostosta("testFiles/hyllyt.dat"); 
    toka.lueTiedostosta("testFiles/hyllyt.dat"); 
    assertEquals("From: Hyllyt line: 201", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/hyllytEri.dat"); 
    assertEquals("From: Hyllyt line: 203", false, uusi.equals(toka)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetLkm225 
   * @throws TietoException when error
   */
  @Test
  public void testGetLkm225() throws TietoException {    // Hyllyt: 225
    Hyllyt hyllyt = new Hyllyt(); 
    assertEquals("From: Hyllyt line: 228", 0, hyllyt.getLkm()); 
    hyllyt.lisaa(new Hylly()); 
    hyllyt.lisaa(new Hylly()); 
    assertEquals("From: Hyllyt line: 231", 2, hyllyt.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna245 
   * @throws TietoException when error
   */
  @Test
  public void testAnna245() throws TietoException {    // Hyllyt: 245
    Hyllyt hyllyt = new Hyllyt(); 
    Hylly uusi = new Hylly(); 
    hyllyt.lisaa(uusi); 
    assertEquals("From: Hyllyt line: 250", true, hyllyt.anna(0).equals(uusi)); 
    try {
    assertEquals("From: Hyllyt line: 251", "error", hyllyt.anna(-5).toString()); 
    fail("Hyllyt: 251 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaeId268 
   * @throws TietoException when error
   */
  @Test
  public void testHaeId268() throws TietoException {    // Hyllyt: 268
    Hyllyt hyllyt = new Hyllyt(); 
    hyllyt.lueTiedostosta("testFiles/hyllyt.dat"); 
    Hylly haku = hyllyt.haeId(1); 
    assertEquals("From: Hyllyt line: 273", "1|1|JAG|0", haku.toString()); 
    try {
    assertEquals("From: Hyllyt line: 274", "", hyllyt.haeId(64).toString()); 
    fail("Hyllyt: 274 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaeIx295 
   * @throws TietoException when error
   */
  @Test
  public void testHaeIx295() throws TietoException {    // Hyllyt: 295
    Hyllyt hyllyt = new Hyllyt(); 
    hyllyt.lisaa("2|1|HAE|0"); 
    hyllyt.lisaa("4|2|JAA|2"); 
    assertEquals("From: Hyllyt line: 300", 0, hyllyt.haeIx(2)); 
    assertEquals("From: Hyllyt line: 301", 1, hyllyt.haeIx(4)); 
    assertEquals("From: Hyllyt line: 302", -1, hyllyt.haeIx(8)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista318 
   * @throws TietoException when error
   */
  @Test
  public void testPoista318() throws TietoException {    // Hyllyt: 318
    Hyllyt hyllyt = new Hyllyt(); 
    hyllyt.lueTiedostosta("testFiles/hyllyt.dat"); 
    assertEquals("From: Hyllyt line: 322", 9, hyllyt.getLkm()); 
    hyllyt.poista(1); 
    hyllyt.poista(5); 
    assertEquals("From: Hyllyt line: 325", 7, hyllyt.getLkm()); 
  } // Generated by ComTest END
}