package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 02:39:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyllyTest {



  // Generated by ComTest BEGIN
  /** testHylly23 */
  @Test
  public void testHylly23() {    // Hylly: 23
    Hylly h = new Hylly(); 
    assertEquals("From: Hylly line: 25", "0|0||0", h.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHylly43 */
  @Test
  public void testHylly43() {    // Hylly: 43
    Hylly uusi = new Hylly(2, 4, "GDA", 6); 
    assertEquals("From: Hylly line: 45", "2|4|GDA|6", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHylly60 */
  @Test
  public void testHylly60() {    // Hylly: 60
    Hylly uusi = new Hylly("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 62", "1|2|ABC|3", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse74 */
  @Test
  public void testParse74() {    // Hylly: 74
    Hylly uusi = new Hylly(); 
    uusi.parse("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 77", "1|2|ABC|3", uusi.toString()); 
    uusi.parse("4|2|DEF|0|"); 
    assertEquals("From: Hylly line: 79", 4, uusi.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa99 */
  @Test
  public void testLisaa99() {    // Hylly: 99
    Hylly uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 101", 0, uusi.getMaara()); 
    uusi.lisaa(); 
    assertEquals("From: Hylly line: 103", 1, uusi.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVahenna115 */
  @Test
  public void testVahenna115() {    // Hylly: 115
    Hylly uusi = new Hylly(1, 2, "JAG", 3); 
    assertEquals("From: Hylly line: 117", 3, uusi.getMaara()); 
    uusi.vahenna(); 
    assertEquals("From: Hylly line: 119", 2, uusi.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetPaikka137 */
  @Test
  public void testSetPaikka137() {    // Hylly: 137
    Hylly h = new Hylly("1|2|ABC|3"); 
    h.setPaikka("BBB"); 
    assertEquals("From: Hylly line: 140", "BBB", h.getPaikka()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetMaara158 */
  @Test
  public void testSetMaara158() {    // Hylly: 158
    Hylly h = new Hylly("1|2|ABC|3"); 
    h.setMaara(5); 
    assertEquals("From: Hylly line: 161", 5, h.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetId173 */
  @Test
  public void testGetId173() {    // Hylly: 173
    Hylly h = new Hylly("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 175", 1, h.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKid186 */
  @Test
  public void testGetKid186() {    // Hylly: 186
    Hylly h = new Hylly("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 188", 2, h.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString200 */
  @Test
  public void testToString200() {    // Hylly: 200
    Hylly uusi = new Hylly(); 
    assertEquals("From: Hylly line: 202", "0|0||0", uusi.toString()); 
    uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 204", "1|2|JAG|0", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTiedot234 */
  @Test
  public void testGetTiedot234() {    // Hylly: 234
    Hylly uusi = new Hylly(); 
    assertEquals("From: Hylly line: 236", "|0", uusi.getTiedot()); 
    uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 238", "JAG|0", uusi.getTiedot()); 
  } // Generated by ComTest END
}