package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 02:15:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyllyTest {



  // Generated by ComTest BEGIN
  /** testHylly22 */
  @Test
  public void testHylly22() {    // Hylly: 22
    Hylly h = new Hylly(); 
    assertEquals("From: Hylly line: 24", "0|0||0", h.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHylly42 */
  @Test
  public void testHylly42() {    // Hylly: 42
    Hylly uusi = new Hylly(2, 4, "GDA", 6); 
    assertEquals("From: Hylly line: 44", "2|4|GDA|6", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHylly59 */
  @Test
  public void testHylly59() {    // Hylly: 59
    Hylly uusi = new Hylly("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 61", "1|2|ABC|3", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse73 */
  @Test
  public void testParse73() {    // Hylly: 73
    Hylly uusi = new Hylly(); 
    uusi.parse("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 76", "1|2|ABC|3", uusi.toString()); 
    uusi.parse("4|2|DEF|0|"); 
    assertEquals("From: Hylly line: 78", 4, uusi.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa98 */
  @Test
  public void testLisaa98() {    // Hylly: 98
    Hylly uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 100", 0, uusi.getMaara()); 
    uusi.lisaa(); 
    assertEquals("From: Hylly line: 102", 1, uusi.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVahenna114 */
  @Test
  public void testVahenna114() {    // Hylly: 114
    Hylly uusi = new Hylly(1, 2, "JAG", 3); 
    assertEquals("From: Hylly line: 116", 3, uusi.getMaara()); 
    uusi.vahenna(); 
    assertEquals("From: Hylly line: 118", 2, uusi.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetPaikka136 */
  @Test
  public void testSetPaikka136() {    // Hylly: 136
    Hylly h = new Hylly("1|2|ABC|3"); 
    h.setPaikka("BBB"); 
    assertEquals("From: Hylly line: 139", "BBB", h.getPaikka()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetMaara157 */
  @Test
  public void testSetMaara157() {    // Hylly: 157
    Hylly h = new Hylly("1|2|ABC|3"); 
    h.setMaara(5); 
    assertEquals("From: Hylly line: 160", 5, h.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetId172 */
  @Test
  public void testGetId172() {    // Hylly: 172
    Hylly h = new Hylly("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 174", 1, h.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKid185 */
  @Test
  public void testGetKid185() {    // Hylly: 185
    Hylly h = new Hylly("1|2|ABC|3"); 
    assertEquals("From: Hylly line: 187", 2, h.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString199 */
  @Test
  public void testToString199() {    // Hylly: 199
    Hylly uusi = new Hylly(); 
    assertEquals("From: Hylly line: 201", "0|0||0", uusi.toString()); 
    uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 203", "1|2|JAG|0", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTiedot233 */
  @Test
  public void testGetTiedot233() {    // Hylly: 233
    Hylly uusi = new Hylly(); 
    assertEquals("From: Hylly line: 235", "|0", uusi.getTiedot()); 
    uusi = new Hylly(1, 2, "JAG", 0); 
    assertEquals("From: Hylly line: 237", "JAG|0", uusi.getTiedot()); 
  } // Generated by ComTest END
}