package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.04 06:13:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriaTest {



  // Generated by ComTest BEGIN
  /** testParse51 */
  @Test
  public void testParse51() {    // Kategoria: 51
    Kategoria uusi = new Kategoria(); 
    uusi.parse("1|Fantasia|Fantasiakirjallisuus on..."); 
    assertEquals("From: Kategoria line: 54", "1|Fantasia|Fantasiakirjallisuus on...", uusi.toString()); 
    uusi.parse("5|Scifi|BlaaBlaa"); 
    assertEquals("From: Kategoria line: 56", "5|Scifi|BlaaBlaa", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMuutaKuvausta105 */
  @Test
  public void testMuutaKuvausta105() {    // Kategoria: 105
    Kategoria uusi = new Kategoria("Fantasia", "Fantasiakirjallisuus on..."); 
    assertEquals("From: Kategoria line: 107", "0|Fantasia|Fantasiakirjallisuus on...", uusi.toString()); 
    uusi.muutaKuvausta("Uusi kuvaus"); 
    assertEquals("From: Kategoria line: 109", "0|Fantasia|Uusi kuvaus", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString132 */
  @Test
  public void testToString132() {    // Kategoria: 132
    Kategoria k1 = new Kategoria(1, "Kategoria", "Esimerkki kuvauksesta"); 
    assertEquals("From: Kategoria line: 134", "1|Kategoria|Esimerkki kuvauksesta", k1.toString()); 
  } // Generated by ComTest END
}