package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.04 05:11:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriatTest {


  // Generated by ComTest BEGIN
  /** 
   * testTallenna80 
   * @throws TietoException when error
   */
  @Test
  public void testTallenna80() throws TietoException {    // Kategoriat: 80
    Kategoriat uusi = new Kategoriat(); 
    Kategoriat toka = new Kategoriat(); 
    uusi.lueTiedostosta("testFiles/testKategoriat.dat"); 
    uusi.tallenna("testFiles/testKategoriatUlos.dat"); 
    toka.lueTiedostosta("testFiles/testKategoriatUlos.dat"); 
    assertEquals("From: Kategoriat line: 87", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/testKategoriatEri.dat"); 
    System.out.println(uusi.equals(toka)); 
    assertEquals("From: Kategoriat line: 90", false, uusi.equals(toka)); 
  } // Generated by ComTest END
}