package kirjasto.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 02:12:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjastoTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa26 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa26() throws TietoException {    // Kirjasto: 26
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lisaa("1|000000|Kirja|Tekija|1900#1|Kategoria|Kuvaus#ABC|10"); 
    assertEquals("From: Kirjasto line: 30", 1, kirjasto.getTeosLkm()); 
    try {
    assertEquals("From: Kirjasto line: 31", 0, kirjasto.lisaa("")); 
    fail("Kirjasto: 31 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista83 
   * @throws TietoException when error
   */
  @Test
  public void testPoista83() throws TietoException {    // Kirjasto: 83
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 87", 9, kirjasto.getTeosLkm()); 
    kirjasto.poista(4); 
    kirjasto.poista(3); 
    assertEquals("From: Kirjasto line: 90", 7, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTyhjenna103 
   * @throws TietoException when error
   */
  @Test
  public void testTyhjenna103() throws TietoException {    // Kirjasto: 103
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 107", 9, kirjasto.getTeosLkm()); 
    kirjasto.tyhjenna(); 
    assertEquals("From: Kirjasto line: 109", 0, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHae126 
   * @throws TietoException when error
   */
  @Test
  public void testHae126() throws TietoException {    // Kirjasto: 126
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    List<Teos> tulokset = kirjasto.hae("", "", "William"); 
    assertEquals("From: Kirjasto line: 132", "6|0-441-56956-0|Neuromancer|William Gibson|1984", tulokset.get(0).toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostostaTest169 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostostaTest169() throws TietoException {    // Kirjasto: 169
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 173", 9, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosLkm188 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosLkm188() throws TietoException {    // Kirjasto: 188
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 192", 9, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeos205 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeos205() throws TietoException {    // Kirjasto: 205
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Teos tulos = kirjasto.getTeos(0); 
    assertEquals("From: Kirjasto line: 210", "1|31-29-6561398-999432-6|The Lord of the Rings|J.R.R. Tolkien|1954", tulos.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetHyllyLkm222 
   * @throws TietoException when error
   */
  @Test
  public void testGetHyllyLkm222() throws TietoException {    // Kirjasto: 222
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 226", 9, kirjasto.getHyllyLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosNimi240 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosNimi240() throws TietoException {    // Kirjasto: 240
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosPaikka258 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosPaikka258() throws TietoException {    // Kirjasto: 258
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 262", "JAG", kirjasto.getTeosPaikka(1)); 
    try {
    assertEquals("From: Kirjasto line: 263", "ERR", kirjasto.getTeosPaikka(25)); 
    fail("Kirjasto: 263 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosMaara278 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosMaara278() throws TietoException {    // Kirjasto: 278
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 282", "0", kirjasto.getTeosMaara(1)); 
    assertEquals("From: Kirjasto line: 283", "2", kirjasto.getTeosMaara(3)); 
    try {
    assertEquals("From: Kirjasto line: 284", "ERR", kirjasto.getTeosMaara(25)); 
    fail("Kirjasto: 284 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna298 
   * @throws TietoException when error
   */
  @Test
  public void testAnna298() throws TietoException {    // Kirjasto: 298
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Hylly tulos = kirjasto.anna(0); 
    assertEquals("From: Kirjasto line: 303", "1|1|JAG|0", tulos.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaeId317 
   * @throws TietoException when error
   */
  @Test
  public void testHaeId317() throws TietoException {    // Kirjasto: 317
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Hylly tulos = kirjasto.haeId(1); 
    assertEquals("From: Kirjasto line: 322", "1|1|JAG|0", tulos.toString()); 
    try {
    assertEquals("From: Kirjasto line: 323", "ERR", kirjasto.haeId(64).toString()); 
    fail("Kirjasto: 323 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTiedot337 
   * @throws TietoException when error
   */
  @Test
  public void testAnnaTiedot337() throws TietoException {    // Kirjasto: 337
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Hylly h = kirjasto.haeId(1); 
    String tulos = kirjasto.annaTiedot(h); 
    assertEquals("From: Kirjasto line: 343", "1|31-29-6561398-999432-6|The Lord of the Rings|J.R.R. Tolkien|1954|1|Fantasia|Fantasiakirjallisuus on kirjallisuuden...|JAG|0", tulos); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTiedot363 
   * @throws TietoException when error
   */
  @Test
  public void testAnnaTiedot363() throws TietoException {    // Kirjasto: 363
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    String tulos = kirjasto.annaTiedot(1); 
    assertEquals("From: Kirjasto line: 368", "1|31-29-6561398-999432-6|The Lord of the Rings|J.R.R. Tolkien|1954|1|Fantasia|Fantasiakirjallisuus on kirjallisuuden...|JAG|0", tulos); 
    try {
    assertEquals("From: Kirjasto line: 369", "ERR", kirjasto.annaTiedot(64)); 
    fail("Kirjasto: 369 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTulostusMuoto395 
   * @throws TietoException when error
   */
  @Test
  public void testTulostusMuoto395() throws TietoException {    // Kirjasto: 395
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    String s = kirjasto.tulostusMuoto(1); 
    assertEquals("From: Kirjasto line: 400", "\nTeoksen nimi    The Lord of the Rings\nKirjailija      J.R.R. Tolkien\nISBN            31-29-6561398-999432-6\nKategoria       Fantasia\nHyllypaikka     JAG\nMaara           0\n----------------------------------", s); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTeoksetTulosteeksi428 
   * @throws TietoException when error
   */
  @Test
  public void testTeoksetTulosteeksi428() throws TietoException {    // Kirjasto: 428
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    ArrayList<Integer> idt = new ArrayList<Integer>(); 
    idt.add(65); 
    try {
    assertEquals("From: Kirjasto line: 435", "ERR", kirjasto.teoksetTulosteeksi(idt)); 
    fail("Kirjasto: 435 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTulostaTeokset453 
   * @throws TietoException when error
   */
  @Test
  public void testTulostaTeokset453() throws TietoException {    // Kirjasto: 453
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    ArrayList<Integer> idt = new ArrayList<Integer>(); 
    idt.add(65); 
    try {
    kirjasto.tulostaTeokset(System.out, idt); 
    fail("Kirjasto: 460 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}