package kirjasto.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.util.ArrayList;
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.23 14:18:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjastoTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa26 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa26() throws TietoException {    // Kirjasto: 26
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lisaa("1|000000|Kirja|Tekija|1900#1|Kategoria|Kuvaus#ABC|10"); 
    assertEquals("From: Kirjasto line: 30", 1, kirjasto.getTeosLkm()); 
    try {
    assertEquals("From: Kirjasto line: 31", 0, kirjasto.lisaa("")); 
    fail("Kirjasto: 31 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista83 
   * @throws TietoException when error
   */
  @Test
  public void testPoista83() throws TietoException {    // Kirjasto: 83
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 87", 9, kirjasto.getTeosLkm()); 
    kirjasto.poista(4); 
    kirjasto.poista(3); 
    assertEquals("From: Kirjasto line: 90", 7, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTyhjenna103 
   * @throws TietoException when error
   */
  @Test
  public void testTyhjenna103() throws TietoException {    // Kirjasto: 103
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 107", 9, kirjasto.getTeosLkm()); 
    kirjasto.tyhjenna(); 
    assertEquals("From: Kirjasto line: 109", 0, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHae126 
   * @throws TietoException when error
   */
  @Test
  public void testHae126() throws TietoException {    // Kirjasto: 126
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    List<Teos> tulokset = kirjasto.hae("", "", "William"); 
    assertEquals("From: Kirjasto line: 132", "7|0-575-03696-6|Count Zero|William Gibson|1987", tulokset.get(0).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTallenna146 
   * @throws TietoException when error
   */
  @Test
  public void testTallenna146() throws TietoException {    // Kirjasto: 146
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostosta("testFiles"); 
    kirjasto.tallenna("testFiles"); 
    Kirjasto kirjasto2 = new Kirjasto(); 
    kirjasto2.lueTiedostosta("testFiles"); 
    assertEquals("From: Kirjasto line: 153", 9, kirjasto2.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta168 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostosta168() throws TietoException {    // Kirjasto: 168
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostosta("testFiles"); 
    assertEquals("From: Kirjasto line: 172", 9, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostostaTest186 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostostaTest186() throws TietoException {    // Kirjasto: 186
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 190", 9, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosLkm205 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosLkm205() throws TietoException {    // Kirjasto: 205
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 209", 9, kirjasto.getTeosLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeos222 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeos222() throws TietoException {    // Kirjasto: 222
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Teos tulos = kirjasto.getTeos(0); 
    assertEquals("From: Kirjasto line: 227", "1|31-29-6561398-999432-6|The Lord of the Rings|J.R.R. Tolkien|1954", tulos.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetHyllyLkm239 
   * @throws TietoException when error
   */
  @Test
  public void testGetHyllyLkm239() throws TietoException {    // Kirjasto: 239
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 243", 9, kirjasto.getHyllyLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosNimi257 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosNimi257() throws TietoException {    // Kirjasto: 257
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosPaikka275 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosPaikka275() throws TietoException {    // Kirjasto: 275
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 279", "JAG", kirjasto.getTeosPaikka(1)); 
    try {
    assertEquals("From: Kirjasto line: 280", "ERR", kirjasto.getTeosPaikka(25)); 
    fail("Kirjasto: 280 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGetTeosMaara295 
   * @throws TietoException when error
   */
  @Test
  public void testGetTeosMaara295() throws TietoException {    // Kirjasto: 295
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    assertEquals("From: Kirjasto line: 299", "0", kirjasto.getTeosMaara(1)); 
    assertEquals("From: Kirjasto line: 300", "2", kirjasto.getTeosMaara(3)); 
    try {
    assertEquals("From: Kirjasto line: 301", "ERR", kirjasto.getTeosMaara(25)); 
    fail("Kirjasto: 301 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna315 
   * @throws TietoException when error
   */
  @Test
  public void testAnna315() throws TietoException {    // Kirjasto: 315
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Hylly tulos = kirjasto.anna(0); 
    assertEquals("From: Kirjasto line: 320", "1|1|JAG|0", tulos.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testHaeId334 
   * @throws TietoException when error
   */
  @Test
  public void testHaeId334() throws TietoException {    // Kirjasto: 334
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Hylly tulos = kirjasto.haeId(1); 
    assertEquals("From: Kirjasto line: 339", "1|1|JAG|0", tulos.toString()); 
    try {
    assertEquals("From: Kirjasto line: 340", "ERR", kirjasto.haeId(64).toString()); 
    fail("Kirjasto: 340 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTiedot354 
   * @throws TietoException when error
   */
  @Test
  public void testAnnaTiedot354() throws TietoException {    // Kirjasto: 354
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    Hylly h = kirjasto.haeId(1); 
    String tulos = kirjasto.annaTiedot(h); 
    assertEquals("From: Kirjasto line: 360", "1|31-29-6561398-999432-6|The Lord of the Rings|J.R.R. Tolkien|1954|1|Fantasia|Fantasiakirjallisuus on kirjallisuuden...|JAG|0", tulos); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTiedot380 
   * @throws TietoException when error
   */
  @Test
  public void testAnnaTiedot380() throws TietoException {    // Kirjasto: 380
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    String tulos = kirjasto.annaTiedot(1); 
    assertEquals("From: Kirjasto line: 385", "1|31-29-6561398-999432-6|The Lord of the Rings|J.R.R. Tolkien|1954|1|Fantasia|Fantasiakirjallisuus on kirjallisuuden...|JAG|0", tulos); 
    try {
    assertEquals("From: Kirjasto line: 386", "ERR", kirjasto.annaTiedot(64)); 
    fail("Kirjasto: 386 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTulostusMuoto412 
   * @throws TietoException when error
   */
  @Test
  public void testTulostusMuoto412() throws TietoException {    // Kirjasto: 412
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    String s = kirjasto.tulostusMuoto(1); 
    assertEquals("From: Kirjasto line: 417", "\nTeoksen nimi    The Lord of the Rings\nKirjailija      J.R.R. Tolkien\nISBN            31-29-6561398-999432-6\nKategoria       Fantasia\nHyllypaikka     JAG\nMaara           0\n----------------------------------", s); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTeoksetTulosteeksi445 
   * @throws TietoException when error
   */
  @Test
  public void testTeoksetTulosteeksi445() throws TietoException {    // Kirjasto: 445
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    ArrayList<Integer> idt = new ArrayList<Integer>(); 
    idt.add(65); 
    try {
    assertEquals("From: Kirjasto line: 452", "ERR", kirjasto.teoksetTulosteeksi(idt)); 
    fail("Kirjasto: 452 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTulostaTeokset470 
   * @throws TietoException when error
   */
  @Test
  public void testTulostaTeokset470() throws TietoException {    // Kirjasto: 470
    Kirjasto kirjasto = new Kirjasto(); 
    kirjasto.lueTiedostostaTest(); 
    ArrayList<Integer> idt = new ArrayList<Integer>(); 
    idt.add(65); 
    try {
    kirjasto.tulostaTeokset(System.out, idt); 
    fail("Kirjasto: 477 Did not throw TietoException");
    } catch(TietoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}