package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.25 15:08:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjastoTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa16 
   * @throws TietoException when error
   */
  @Test
  public void testLisaa16() throws TietoException {    // Kirjasto: 16
    Kirjasto kirjasto = new Kirjasto(); 
    Aineisto k1 = new Aineisto(), k2 = new Aineisto(); 
    k1.vastaaLotr(); k2.vastaaLotr(); 
    assertEquals("From: Kirjasto line: 21", 0, kirjasto.getLkm()); 
    kirjasto.lisaa(k1); kirjasto.lisaa(k2); 
    assertEquals("From: Kirjasto line: 23", 2, kirjasto.getLkm()); 
    assertEquals("From: Kirjasto line: 24", k1, kirjasto.annaKirja(0)); 
    assertEquals("From: Kirjasto line: 25", k2, kirjasto.annaKirja(1)); 
    try {
    kirjasto.annaKirja(3); 
    fail("Kirjasto: 26 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjasto.lisaaLotr(); 
    assertEquals("From: Kirjasto line: 28", 3, kirjasto.getLkm()); 
  } // Generated by ComTest END
}