package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.04 06:12:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TeoksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testTallenna60 
   * @throws TietoException when error
   */
  @Test
  public void testTallenna60() throws TietoException {    // Teokset: 60
    Teokset uusi = new Teokset(); 
    Teokset toka = new Teokset(); 
    uusi.lueTiedostosta("testFiles/Teokset.dat"); 
    uusi.tallenna("testFiles/TeoksetUlos.dat"); 
    toka.lueTiedostosta("testFiles/TeoksetUlos.dat"); 
    assertEquals("From: Teokset line: 67", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/TeoksetEri.dat"); 
    System.out.println(uusi.equals(toka)); 
    assertEquals("From: Teokset line: 70", false, uusi.equals(toka)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta88 
   * @throws TietoException when error
   */
  @Test
  public void testLueTiedostosta88() throws TietoException {    // Teokset: 88
    Teokset uusi = new Teokset(); 
    Teokset toka = new Teokset(); 
    uusi.lueTiedostosta("testFiles/Teokset.dat"); 
    toka.lueTiedostosta("testFiles/Teokset.dat"); 
    assertEquals("From: Teokset line: 94", true, uusi.equals(toka)); 
    toka.lueTiedostosta("testFiles/TeoksetEri.dat"); 
    assertEquals("From: Teokset line: 96", false, uusi.equals(toka)); 
    assertEquals("From: Teokset line: 97", 3, uusi.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEquals119 
   * @throws TietoException when error
   */
  @Test
  public void testEquals119() throws TietoException {    // Teokset: 119
    Teokset tama = new Teokset(); 
    Teokset toinen = new Teokset(); 
    tama.lueTiedostosta("testFiles/Teokset.dat"); 
    toinen.lueTiedostosta("testFiles/Teokset.dat"); 
    assertEquals("From: Teokset line: 125", true, tama.equals(toinen)); 
    toinen.lueTiedostosta("testFiles/TeoksetEri.dat"); 
    assertEquals("From: Teokset line: 127", false, tama.equals(toinen)); 
  } // Generated by ComTest END
}