package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.24 23:46:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TeosTest {



  // Generated by ComTest BEGIN
  /** testToString54 */
  @Test
  public void testToString54() {    // Teos: 54
    Teos t1 = new Teos(); 
    assertEquals("From: Teos line: 56", "0||||0", t1.toString()); 
    t1.vastaaLotr(); 
    assertEquals("From: Teos line: 58", "3|978-0544003415|The Lord of the Rings|J.R.R. Tolkien|1954", t1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi75 */
  @Test
  public void testRekisteroi75() {    // Teos: 75
    Teos t1 = new Teos(); 
    assertEquals("From: Teos line: 77", 0, t1.getId()); 
    t1.rekisteroi(); 
    assertEquals("From: Teos line: 79", 1, t1.getId()); 
    Teos t2 = new Teos(); 
    t2.rekisteroi(); 
    assertEquals("From: Teos line: 82", 2, t2.getId()); 
    int n1 = t1.getId(); 
    int n2 = t2.getId(); 
    assertEquals("From: Teos line: 85", n2 - 1, n1); 
  } // Generated by ComTest END
}