package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.02 01:46:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TeosTest {



  // Generated by ComTest BEGIN
  /** testTeos37 */
  @Test
  public void testTeos37() {    // Teos: 37
    Teos uusi = new Teos("1|123-123-123-123|Uusi Kirja|Matti Meikalainen|1995"); 
    assertEquals("From: Teos line: 39", "1|123-123-123-123|Uusi Kirja|Matti Meikalainen|1995", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse51 */
  @Test
  public void testParse51() {    // Teos: 51
    Teos uusi = new Teos(); 
    uusi.parse("1|123-123-123-123|Uusi Kirja|Matti Meikalainen|1995"); 
    assertEquals("From: Teos line: 54", "1|123-123-123-123|Uusi Kirja|Matti Meikalainen|1995", uusi.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString99 */
  @Test
  public void testToString99() {    // Teos: 99
    Teos t1 = new Teos(); 
    assertEquals("From: Teos line: 101", "0||||0", t1.toString()); 
    t1.vastaaLotr(); 
    assertEquals("From: Teos line: 103", "1|978-0544003415|The Lord of the Rings|J.R.R. Tolkien|1954", t1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi120 */
  @Test
  public void testRekisteroi120() {    // Teos: 120
    Teos t1 = new Teos(); 
    assertEquals("From: Teos line: 122", 0, t1.getId()); 
    t1.rekisteroi(); 
    assertEquals("From: Teos line: 124", 2, t1.getId()); 
    Teos t2 = new Teos(); 
    t2.rekisteroi(); 
    assertEquals("From: Teos line: 127", 3, t2.getId()); 
    int n1 = t1.getId(); 
    int n2 = t2.getId(); 
    assertEquals("From: Teos line: 130", n2 - 1, n1); 
  } // Generated by ComTest END
}