package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.04 20:50:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TeosTest {



  // Generated by ComTest BEGIN
  /** testToString39 */
  @Test
  public void testToString39() {    // Teos: 39
    Teos t1 = new Teos(); 
    assertEquals("From: Teos line: 41", "0||||0", t1.toString()); 
    t1.vastaaLotr(); 
    assertEquals("From: Teos line: 43", "0|978-0544003415|The Lord of the Rings|J.R.R. Tolkien|1954", t1.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi60 */
  @Test
  public void testRekisteroi60() {    // Teos: 60
    Teos t1 = new Teos(); 
    assertEquals("From: Teos line: 62", 0, t1.getId()); 
    t1.rekisteroi(); 
    assertEquals("From: Teos line: 64", 1, t1.getId()); 
    Teos t2 = new Teos(); 
    t2.rekisteroi(); 
    assertEquals("From: Teos line: 67", 2, t2.getId()); 
    int n1 = t1.getId(); 
    int n2 = t2.getId(); 
    assertEquals("From: Teos line: 70", n2 - 1, n1); 
  } // Generated by ComTest END
}